version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: climbing_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    environment:
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - climbing_net

volumes:
  redis_data:
    name: climbing_redis_data

networks:
  climbing_net:
    name: climbing_network
    driver: bridge 
