[project]
name = "link-preview-server"
version = "1.0.0"
description = "A modern Python server to fetch link metadata."
dependencies = [
    "fastapi>=0.111.0",
    "uvicorn[standard]>=0.29.0",
    "httpx>=0.27.0",
    "beautifulsoup4>=4.12.3",
]
requires-python = ">=3.13"
