[project]
name = "climbing"
version = "1.0.0"
description = ""
dependencies = [
    "fastapi>=0.111.0",
    "uvicorn[standard]>=0.29.0",
    "httpx>=0.27.0",
    "beautifulsoup4>=4.12.3",
    "gunicorn>=22.0.0",
]
requires-python = ">=3.13"
